# https://www.irasutoya.com/2017/08/blog-post_313.html
IKA_URL := https://3.bp.blogspot.com/-cyF7po_IL_4/WYAx9EHo9DI/AAAAAAABFxA/zuPU_uVv-EIQm5uPgwgl4nGyDO1ZOysRwCLcBGAs/s800/character_fish_ika.png
# https://www.irasutoya.com/2013/01/blog-post_31.html
TAKO_URL := https://3.bp.blogspot.com/-eU_OyQeEmFU/UnXnKHxZdoI/AAAAAAAAaI4/AtK1-8NE9UQ/s800/fish_tako.png

TARGETS := \
	eto \
	inkling.png \
	octoling.png

all: $(TARGETS)
.PHONY: all eto

inkling.png:
	curl -fsSL -o $@ $(IKA_URL)

octoling.png:
	curl -fsSL -o $@ $(TAKO_URL)

eto: eto/0.png eto/1.png eto/2.png eto/3.png eto/4.png eto/5.png eto/6.png eto/7.png eto/8.png eto/9.png eto/10.png eto/11.png

eto/0.png:
	curl -fsSL -o $@ https://4.bp.blogspot.com/-oSKf9hanjZQ/VCOJRVRiFJI/AAAAAAAAmvM/gQcL6jUm-HE/s800/eto_mark01_nezumi.png

eto/1.png:
	curl -fsSL -o $@ https://4.bp.blogspot.com/-bMsgnav8nno/VCOJRzUeoVI/AAAAAAAAmu0/cbGrWqzC2hc/s800/eto_mark02_ushi.png

eto/2.png:
	curl -fsSL -o $@ https://1.bp.blogspot.com/-XIN5WzvTdSQ/VCOJSFAq98I/AAAAAAAAmu4/mrjNpVyR13o/s800/eto_mark03_tora.png

eto/3.png:
	curl -fsSL -o $@ https://2.bp.blogspot.com/-sCYd5MsquF4/VCOJS6eoLvI/AAAAAAAAmvE/EDFPg_-YdmQ/s800/eto_mark04_usagi.png
	
eto/4.png:
	curl -fsSL -o $@ https://1.bp.blogspot.com/-7OzCCLysaWY/VCOJTY7fF5I/AAAAAAAAmvY/HqoY2F8aEqA/s800/eto_mark05_tatsu.png

eto/5.png:
	curl -fsSL -o $@ https://4.bp.blogspot.com/-EwTBe_PVaPM/VCOJTyKzgXI/AAAAAAAAmvU/1wxwG9Ij8NY/s800/eto_mark06_hebi.png

eto/6.png:
	curl -fsSL -o $@ https://2.bp.blogspot.com/-763vLEAtakc/VCOJUdnPPkI/AAAAAAAAmv4/Z6WP874jNMA/s800/eto_mark07_uma.png

eto/7.png:
	curl -fsSL -o $@ https://4.bp.blogspot.com/-VLWooGuODXQ/VCOJVO9PCmI/AAAAAAAAmvk/LHUUqeHpCE0/s800/eto_mark08_hitsuji.png

eto/8.png:
	curl -fsSL -o $@ https://4.bp.blogspot.com/-8JYVELlSe8Y/VCOJVfrEMAI/AAAAAAAAmvo/4Tya5TkVZxQ/s800/eto_mark09_saru.png

eto/9.png:
	curl -fsSL -o $@ https://3.bp.blogspot.com/-5-dW591Z9j0/VCOJWCuCgyI/AAAAAAAAmv8/_ZkMXKk5Y8U/s800/eto_mark10_tori.png

eto/10.png:
	curl -fsSL -o $@ https://2.bp.blogspot.com/-qNz5DXF_6lo/VCOJWh4xdQI/AAAAAAAAmwE/0PTCP7qHb50/s800/eto_mark11_inu.png

eto/11.png:
	curl -fsSL -o $@ https://4.bp.blogspot.com/-e5GvAc2KkKM/VCOJXLJEj-I/AAAAAAAAmwM/RqM5twBmVQo/s800/eto_mark12_inoshishi.png
