all: inkling.png octoling.png
.PHONY: all

inkling.png:
	curl -o $@ 'https://3.bp.blogspot.com/-1YQ0kl1rNQw/Wfg1aXr2gHI/AAAAAAABH6I/FHwzUCSSk-EScozQeEkLo68U_FDbbA39ACLcBGAs/s800/allergy_ika.png'

octoling.png:
	curl -o $@ 'https://1.bp.blogspot.com/-hZDnxHhNn1g/Wfg1aokUkPI/AAAAAAABH6M/N_rFrot_gtYIJIKkUBuaQIBeLmEf4NDzACLcBGAs/s800/allergy_tako.png'
