# https://www.irasutoya.com/2017/08/blog-post_313.html
IKA_URL := https://3.bp.blogspot.com/-cyF7po_IL_4/WYAx9EHo9DI/AAAAAAABFxA/zuPU_uVv-EIQm5uPgwgl4nGyDO1ZOysRwCLcBGAs/s800/character_fish_ika.png
# https://www.irasutoya.com/2013/01/blog-post_31.html
TAKO_URL := https://3.bp.blogspot.com/-eU_OyQeEmFU/UnXnKHxZdoI/AAAAAAAAaI4/AtK1-8NE9UQ/s800/fish_tako.png

all: inkling.png octoling.png
.PHONY: all

inkling.png:
	curl -o $@ $(IKA_URL)

octoling.png:
	curl -o $@ $(TAKO_URL)
