<?php

/**
 * @copyright Copyright (C) 2024-2025 AIZAWA Hina
 * @license https://github.com/fetus-hina/stat.ink/blob/master/LICENSE MIT
 * @author AIZAWA Hina <hina@fetus.jp>
 */

declare(strict_types=1);

return [
    'map' => [
        'AIZAWA Hina <hina@bouhime.com>' => 'AIZAWA Hina <hina@fetus.jp>',
        'AIZAWA, Hina <hina@bouhime.com>' => 'AIZAWA Hina <hina@fetus.jp>',
        'GitHub <noreply@github.com>' => null,
        'Lukas <github@muffl0n.de>' => 'Lukas Böttcher <github@muffl0n.de>',
        'StyleCI Bot <bot@styleci.io>' => null,
        'Unknown <wkoichi@gmail.com>' => 'Koichi Watanabe <wkoichi@gmail.com>',
        'Yifan <44556003+liuyifan-eric@users.noreply.github.com>' => 'Yifan Liu <yifanliu00@gmail.com>',
        'li <170cm.kurekure@gmail.com>' => 'li <nvblstr@gmail.com>',
        'spacemeowx2 <spacemeowx2@gmail.com>' => 'imspace <spacemeowx2@gmail.com>',
    ],
    'copyLeft' => [
        'clovervidia <clovervidia@gmail.com>' => [
            'messages/en-GB/weapon-short.php',
            'messages/en/weapon-short.php',
        ],
        'Gosin <canling0@gmail.com>' => [
            'messages/zh-TW/ability.php',
            'messages/zh-TW/ability2.php',
            'messages/zh-TW/alert.php',
            'messages/zh-TW/apidoc1.php',
            'messages/zh-TW/apidoc2.php',
            'messages/zh-TW/app.php',
            'messages/zh-TW/brand.php',
            'messages/zh-TW/brand2.php',
            'messages/zh-TW/cookie.php',
            'messages/zh-TW/counter.php',
            'messages/zh-TW/death.php',
            'messages/zh-TW/death2.php',
            'messages/zh-TW/email.php',
            'messages/zh-TW/event.php',
            'messages/zh-TW/fest.php',
            'messages/zh-TW/festpower2.php',
            'messages/zh-TW/freshness2.php',
            'messages/zh-TW/gear.php',
            'messages/zh-TW/gear2.php',
            'messages/zh-TW/gearstat.php',
            'messages/zh-TW/link.php',
            'messages/zh-TW/map.php',
            'messages/zh-TW/map2.php',
            'messages/zh-TW/privacy.php',
            'messages/zh-TW/rank.php',
            'messages/zh-TW/rank2.php',
            'messages/zh-TW/region.php',
            'messages/zh-TW/rule.php',
            'messages/zh-TW/rule2.php',
            'messages/zh-TW/salmon-boss2.php',
            'messages/zh-TW/salmon-event2.php',
            'messages/zh-TW/salmon-history2.php',
            'messages/zh-TW/salmon-map2.php',
            'messages/zh-TW/salmon-tide2.php',
            'messages/zh-TW/salmon-title2.php',
            'messages/zh-TW/salmon2.php',
            'messages/zh-TW/slack.php',
            'messages/zh-TW/special.php',
            'messages/zh-TW/special2.php',
            'messages/zh-TW/start.php',
            'messages/zh-TW/subweapon.php',
            'messages/zh-TW/subweapon2.php',
            'messages/zh-TW/ua_vars.php',
            'messages/zh-TW/ua_vars_v.php',
            'messages/zh-TW/version2.php',
            'messages/zh-TW/weapon-short.php',
            'messages/zh-TW/weapon.php',
            'messages/zh-TW/weapon2.php',
        ],
        'midmiako <mayomi@baka.wang>' => [
            'messages/zh-CN/map3.php',
            'messages/zh-TW/map3.php',
        ],
        'ultrasonicytb <ultrasonic2408@gmail.com>' => [
            'messages/fr/ability.php',
            'messages/fr/ability2.php',
            'messages/fr/alert.php',
            'messages/fr/app.php',
            'messages/fr/brand.php',
            'messages/fr/cookie.php',
            'messages/fr/counter.php',
            'messages/fr/death.php',
            'messages/fr/death2.php',
            'messages/fr/email.php',
            'messages/fr/freshness2.php',
            'messages/fr/map.php',
            'messages/fr/map2.php',
            'messages/fr/map3.php',
            'messages/fr/privacy.php',
            'messages/fr/region.php',
            'messages/fr/reltime.php',
            'messages/fr/rule.php',
            'messages/fr/rule2.php',
            'messages/fr/salmon-history2.php',
            'messages/fr/salmon-tide2.php',
            'messages/fr/salmon-title2.php',
            'messages/fr/salmon2.php',
            'messages/fr/special2.php',
            'messages/fr/start.php',
            'messages/fr/version2.php',
            'messages/fr/weapon.php',
            'messages/fr/weapon2.php',
        ],
    ],
];
