<?php
return [
    'enablePrettyUrl' => true,
    'showScriptName' => false,
    'enableStrictParsing' => true,
    'rules' => [
        'login'         => 'user/login',
        'logout'        => 'user/logout',
        'profile'       => 'user/profile',
        'register'      => 'user/register',
        'u/<screen_name:\w+>/<battle:\d+>' => 'show/battle',
        'u/<screen_name:\w+>/<battle:\d+>/edit' => 'show/edit-battle',
        'u/<screen_name:\w+>/<id_from:\d+>-<id_to:\d+>' => 'show/user',
        'u/<screen_name:\w+>/stat/report/<year:\d+>/<month:\d+>' => 'show/user-stat-report',
        'u/<screen_name:\w+>/stat/report/<year:\d+>' => 'show/user-stat-report',
        'u/<screen_name:\w+>/stat/<by:[\w-]+>' => 'show/user-stat-<by>',
        'u/<screen_name:\w+>' => 'show/user',
        'u/<screen_name:\w+>.<lang:[\w-]+>.<type:rss|atom>' => 'feed/user',
        'fest/<region:\w+>/<order:\d+>' => 'fest/view',
        'entire/weapons/<weapon:\w+>/<rule:\w+>' => 'entire/weapon',
        'entire/weapons/<weapon:\w+>' => 'entire/weapon',
        'entire/users/combined-<b32name:[A-Za-z2-7]+>' => 'entire/combined-agent',
        'entire/users/<b32name:[A-Za-z2-7]+>' => 'entire/agent',
        'stages/<year:\d+>/<month:\d+>' => 'stage/month',
        'stages/<map:[a-z]+>/<rule:[a-z0-9_]+>.json' => 'stage/map-history-json',
        'stages/<map:[a-z]+>/<rule:[a-z0-9_]+>' => 'stage/map-detail',
        'stages/<map:[a-z]+>' => 'stage/map',
        'stages' => 'stage/index',
        'api/v1/<action:[\w-]+>' => 'api-v1/<action>',
        'api/internal/<action:[\w-]+>' => 'api-internal/<action>',
        'downloads' => 'download-stats/index',
        '<action:[\w-]+>'  => 'site/<action>',
        '<controller:[\w-]+>/<action:[\w-]+>' => '<controller>/<action>',
        'robots.txt'    => 'site/robots',
        ''              => 'site/index',
    ],
];
